// This file was automatically generated by "compat-table.js"

package compat

type Engine uint8

const (
	Android Engine = iota
	Chrome
	Edge
	Firefox
	Ios
	Node
	Safari
)

type Feature uint8

const (
	Async Feature = iota
	AsyncIter
	BigInt
	ClassField
	ClassPrivateField
	ClassPrivateMethod
	ClassPrivateStaticField
	ClassPrivateStaticMethod
	ClassStaticField
	ExponentOperator
	Hashbang
	LogicalAssignment
	NestedRestBinding
	NullishCoalescing
	ObjectRestSpread
	OptionalCatchBinding
	OptionalChain
)

var Table = map[Feature]map[Engine]float32{
	Async: map[Engine]float32{
		Chrome:  55,
		Edge:    15,
		Firefox: 52,
		Ios:     10.3,
		Node:    7.6,
		Safari:  10.1,
	},
	AsyncIter: map[Engine]float32{
		Chrome:  63,
		Edge:    79,
		Firefox: 57,
		Ios:     12,
		Node:    10,
		Safari:  12,
	},
	BigInt: map[Engine]float32{
		Chrome:  67,
		Edge:    79,
		Firefox: 68,
		Node:    10.4,
		Safari:  14,
	},
	ClassField: map[Engine]float32{
		Chrome:  72,
		Edge:    79,
		Firefox: 69,
		Node:    12,
		Safari:  14,
	},
	ClassPrivateField: map[Engine]float32{
		Chrome: 74,
		Edge:   79,
		Node:   12,
	},
	ClassPrivateMethod: map[Engine]float32{
		Chrome: 84,
	},
	ClassPrivateStaticField: map[Engine]float32{
		Chrome: 74,
		Edge:   79,
		Node:   12,
	},
	ClassPrivateStaticMethod: map[Engine]float32{
		Chrome: 84,
	},
	ClassStaticField: map[Engine]float32{
		Chrome:  72,
		Edge:    79,
		Firefox: 75,
		Node:    12,
	},
	ExponentOperator: map[Engine]float32{
		Chrome:  52,
		Edge:    14,
		Firefox: 52,
		Ios:     10.3,
		Node:    7,
		Safari:  10.1,
	},
	Hashbang: map[Engine]float32{
		Chrome:  74,
		Edge:    79,
		Firefox: 67,
		Ios:     13.4,
		Node:    12,
		Safari:  13.1,
	},
	LogicalAssignment: map[Engine]float32{
		Chrome:  85,
		Firefox: 79,
		Safari:  14,
	},
	NestedRestBinding: map[Engine]float32{
		Chrome:  49,
		Edge:    14,
		Firefox: 47,
		Ios:     10.3,
		Node:    6,
		Safari:  10.1,
	},
	NullishCoalescing: map[Engine]float32{
		Chrome:  80,
		Edge:    80,
		Firefox: 72,
		Ios:     13.4,
		Node:    14,
		Safari:  13.1,
	},
	ObjectRestSpread: map[Engine]float32{
		Chrome:  60,
		Edge:    79,
		Firefox: 55,
		Ios:     11.3,
		Node:    8.1,
		Safari:  11.1,
	},
	OptionalCatchBinding: map[Engine]float32{
		Chrome:  66,
		Edge:    79,
		Firefox: 58,
		Ios:     11.3,
		Node:    10,
		Safari:  11.1,
	},
	OptionalChain: map[Engine]float32{
		Chrome:  80,
		Edge:    80,
		Firefox: 74,
		Ios:     13.4,
		Node:    14,
		Safari:  13.1,
	},
}
