// This file was automatically generated by "compat-table.js"

package cli

import "github.com/evanw/esbuild/pkg/api"

var validEngines = map[string]api.EngineName{
	"chrome":  api.EngineChrome,
	"deno":    api.EngineDeno,
	"edge":    api.EngineEdge,
	"firefox": api.EngineFirefox,
	"hermes":  api.EngineHermes,
	"ie":      api.EngineIE,
	"ios":     api.EngineIOS,
	"node":    api.EngineNode,
	"opera":   api.EngineOpera,
	"rhino":   api.EngineRhino,
	"safari":  api.EngineSafari,
}
